"""
report_assembler.py
===================
Generates structured medical report from a concluded session.
Includes patient location, local time, and timezone in metadata.
"""

import anthropic
from datetime import datetime, timezone
from langsmith import traceable
from config import settings
from services.memory_service import (
    supabase, get_user_profile, get_history,
    get_session_files, get_session_conclusion
)

client = anthropic.Anthropic(api_key=settings.anthropic_api_key)


@traceable(name="report-assembler")
def assemble_report(session_id: str, user_id: str) -> dict:
    """
    Assemble complete medical consultation report.
    Includes full patient context: profile, symptoms, diagnoses,
    MCP enrichment, uploaded files, location, and local time.
    """
    profile    = get_user_profile(user_id)
    history    = get_history(session_id)
    files      = get_session_files(session_id)
    conclusion = get_session_conclusion(session_id)

    diagnoses    = conclusion.get("final_diagnoses", [])
    mcp          = conclusion.get("mcp_enrichment", {})
    location     = conclusion.get("location", {})
    tz           = conclusion.get("timezone", "UTC")
    local_time   = conclusion.get("concluded_at_local", "")

    user_messages = [m["content"] for m in history if m["role"] == "user"]
    summary       = _generate_summary(profile, diagnoses, mcp, user_messages, location, local_time)

    # Format consultation time for display
    display_time = _format_display_time(local_time, tz)

    report = {
        "report_metadata": {
            "generated_at":       datetime.now(timezone.utc).isoformat(),
            "session_id":         session_id,
            "consultation_time":  display_time,
            "patient_timezone":   tz,
            "patient_location":   _format_location(location),
            "disclaimer": (
                "This report was generated by MurphyBot, an AI-assisted "
                "medical consultation tool. It is NOT a clinical diagnosis. "
                "Please present this to a qualified healthcare professional "
                "for proper evaluation and treatment."
            )
        },
        "patient_profile":       _format_profile(profile),
        "consultation_summary": {
            "total_turns":   len(user_messages),
            "plain_summary": summary
        },
        "differential_diagnoses": [
            {
                "disease":    d["disease"],
                "score":      d.get("score", d.get("match_ratio", 0)),
                "confidence": _score_to_confidence(
                    d.get("score", d.get("match_ratio", 0))
                )
            }
            for d in diagnoses
        ],
        "confirmatory_tests": mcp.get("tests", []),
        "medications": [
            {
                "name":              drug.get("name", ""),
                "brand_name":        drug.get("brand_name", ""),
                "indications":       drug.get("indications", ""),
                "warnings":          drug.get("warnings", ""),
                "contraindications": drug.get("contraindications", "")
            }
            for drug in mcp.get("drugs", [])
            if drug.get("available")
        ],
        "drug_interactions":      mcp.get("interactions", []),
        "clinical_guidelines":    mcp.get("guidelines", {}),
        "pubmed_references": [
            {
                "title":   p.get("title", ""),
                "authors": p.get("authors", ""),
                "journal": p.get("journal", ""),
                "year":    p.get("year", ""),
                "url":     p.get("url", "")
            }
            for p in mcp.get("pubmed_papers", [])
        ],
        "uploaded_file_analyses":    files,
        "conversation_transcript": [
            {"role": m["role"], "content": m["content"]}
            for m in history
        ]
    }

    return report


def _generate_summary(
    profile:       dict | None,
    diagnoses:     list[dict],
    mcp:           dict,
    user_messages: list[str],
    location:      dict,
    local_time:    str
) -> str:
    """Claude generates a plain-language summary for the doctor."""
    if not diagnoses:
        return "Consultation did not reach a conclusion."

    parts = []
    if profile:
        if profile.get("age"):  parts.append(f"{profile['age']}-year-old")
        if profile.get("sex"):  parts.append(profile["sex"])
    profile_str = " ".join(parts)

    top_diagnosis  = diagnoses[0]["disease"] if diagnoses else "unknown"
    drug_names     = [d["name"] for d in mcp.get("drugs", []) if d.get("name")]
    test_names     = [t.get("test", "") for t in mcp.get("tests", [])[:3]]
    symptom_sample = user_messages[0][:200] if user_messages else ""
    loc_str        = location.get("location_text", "") if location else ""
    time_str       = local_time or ""

    prompt = f"""Write a 2-3 sentence clinical summary of this AI-assisted consultation.
Address it to a doctor reading the patient's report.
Be concise and factual. Use clinical language.

Patient: {profile_str}
Location: {loc_str}
Consultation time: {time_str}
Chief complaint: {symptom_sample}
Top diagnosis: {top_diagnosis} (AI-assisted, graph-derived)
Other candidates: {', '.join(d['disease'] for d in diagnoses[1:3])}
Suggested medications: {', '.join(drug_names) or 'none'}
Recommended tests: {', '.join(test_names) or 'none'}

Write only the summary. No preamble."""

    try:
        response = client.messages.create(
            model="claude-sonnet-4-20250514",
            max_tokens=200,
            messages=[{"role": "user", "content": prompt}]
        )
        return response.content[0].text.strip()
    except Exception:
        return (
            f"AI-assisted consultation for {profile_str} patient. "
            f"Top differential: {top_diagnosis}. Full details below."
        )


def _format_display_time(local_time: str, tz: str) -> str:
    """Format local time for human-readable display in report."""
    if not local_time:
        return datetime.now(timezone.utc).strftime("%B %d, %Y at %H:%M UTC")
    try:
        # Parse ISO string — e.g. "2026-03-13T15:45:00"
        dt = datetime.fromisoformat(local_time)
        tz_label = tz if tz else "local time"
        return dt.strftime(f"%B %d, %Y at %I:%M %p") + f" ({tz_label})"
    except Exception:
        return local_time


def _format_location(location: dict | None) -> str:
    """Format location dict into human-readable string."""
    if not location:
        return "Not provided"
    if location.get("location_text"):
        return location["location_text"]
    if location.get("lat") and location.get("lng"):
        return f"{location['lat']:.4f}, {location['lng']:.4f}"
    return "Not provided"


def _format_profile(profile: dict | None) -> dict:
    if not profile:
        return {"available": False}
    return {
        "available":           True,
        "age":                 profile.get("age"),
        "sex":                 profile.get("sex"),
        "blood_type":          profile.get("blood_type"),
        "chronic_conditions":  profile.get("chronic_conditions", []),
        "current_medications": profile.get("current_medications", []),
        "allergies":           profile.get("allergies", []),
        "past_surgeries":      profile.get("past_surgeries", [])
    }


def _score_to_confidence(score: float) -> str:
    if score >= 0.7:  return "High"
    if score >= 0.5:  return "Medium"
    return "Low"